#!/bin/bash

# You may need to add/remove some calls to `sudo` in `build-deb` to get this to work. In CI `build-deb` does not run
# in a container so the user environment is slightly different.

set -ex

docker buildx build \
    --build-arg BUILD_PG=$1 \
    --build-arg BUILD_PY=$2 \
    --build-arg PACKAGE_NAME=$3 \
    --build-arg TEST=$4 \
    --target=artifact \
    --output build \
    -f Dockerfile.builder \
    .
