#!/bin/bash

set -e
set -x

mkdir -p build
cd build

if [[ $1 == "ON" ]]; then
    EXTRA_FLAGS="-DPostgreSQL_ROOT=/usr -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/14/server/"
fi

cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DINCHI_URL=https://raw.githubusercontent.com/cdd/inchi-downloads/main/INCHI-1-SRC.zip \
    -DRDK_BUILD_CAIRO_SUPPORT=ON \
    -DRDK_BUILD_INCHI_SUPPORT=ON \
    -DRDK_BUILD_PGSQL=$1 \
    -DRDK_BUILD_PYTHON_WRAPPERS=$2 \
    -DRDK_INSTALL_INTREE=OFF \
    -DCMAKE_POLICY_DEFAULT_CMP0074=NEW ${EXTRA_FLAGS}


if [[ $5 != "NODEB" ]]; then
    UPSTREAM_VERSION=$(<../UPSTREAM_VERSION)
    CDD_VERSION=$(<../CDD_VERSION)

    sudo checkinstall \
        --pakdir .. \
        --backup=no \
        --install=no \
        --nodoc \
        --pkgname $3 \
        --pkgversion $UPSTREAM_VERSION \
        --pkgrelease $CDD_VERSION \
        -y \
        make -j$(nproc) install
fi

if [[ $4 == "TEST" ]]; then
    make -j$(nproc)
    sudo make -j$(nproc) install
    sudo ldconfig
    export RDBASE=`pwd`/..
    if [[ $1 == "ON" ]]; then
        sudo sh ./Code/PgSQL/rdkit/pgsql_install.sh
        sudo service postgresql restart
    fi
    if [[ $2 == "ON" ]]; then
        sudo sh -c 'echo "/usr/local/lib/python3/dist-packages/" > /usr/local/lib/python3.10/dist-packages/rdkit.pth'
    fi
    ctest --output-on-failure
    if [[ $1 == "ON" ]]; then
        sh ./Code/PgSQL/rdkit/pgsql_regress.sh
        if [ -e ./Code/PgSQL/rdkit/regression.diffs ]
        then
            cat ./Code/PgSQL/rdkit/regression.diffs
            exit 1
        fi
    fi
fi
