name: Build deb package

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      skip-tests:
        type: "string"
        description: "Skip tests"
        required: false
        default: "false"
  push:

jobs:
  build_deb:
    strategy:
      matrix:
        arch: [[self-hosted, linux, x64, rdkit], [self-hosted, linux, arm64, rdkit]]
        variant: [
          {pg: OFF, py: OFF, pkg: rdkit},
          {pg: ON, py: OFF, pkg: rdkit-pg},
          {pg: OFF, py: ON, pkg: rdkit-py}
        ]
      fail-fast: false
    runs-on: ${{matrix.arch}}
    env:
      DEB_PACKAGE: ${{matrix.variant.pkg}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-west-2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        run: ./build-and-push ${{matrix.variant.pg}} ${{matrix.variant.py}} ${{matrix.variant.pkg}} ${{ github.event.inputs.skip-tests == 'true' && 'NO-TESTS' }}
